/**
 * Shared Nyau locations for chapters 4–6, so the city stays the same place
 * from chapter to chapter: the aerodock (three docking piers, the Itaka's
 * berth at the third pylon, the warehouses, the dock tavern), the Temple of
 * El (mosaic hall, inner garden with the niche, colonnade, Soril's study,
 * courtyard and gate), and the garden beyond the old canal.
 */
import type { MapDef, PlacedProp, Vec2 } from '../../../types'

// ============================================================================ aerodock (34 x 26)

export const dockMap: MapDef = {
  rows: [
    'WWWWWW~~DdddD~~~DdddD~~~DdddddD~~~',
    'WWWWWW~~ddddd~~~ddddd~~~ddddddd~~~',
    'WWWWWW~~ddddd~~~ddddd~~~ddddddd~~~',
    'WWWWWW~~ddddd~~~ddddd~~~ddddddd~~~',
    'WWWWWW~~DdddD~~~DdddD~~~DdddddD~~~',
    'WWWWWW~~ddddd~~~ddddd~~~ddddddd~~~',
    'WWWWWW~~ddddd~~~ddddd~~~ddddddd~~~',
    'WWWWWW~~ddddd~~~ddddd~~~ddddddd~~~',
    'WWWWWW~~DdddD~~~DdddD~~~DdddddD~~~',
    'WWWWWWdddddddddddddddddddddddddddd',
    'WWWWWWdddddddddddddddddddddddddddd',
    'aaaaaadddddddddddddddddddddddddddd',
    'aaaaaa.....,..........,...........',
    'WWWWWW..............,.......ffffff',
    'WWWWWW.....,................Frrrrr',
    'WWWWWW.................,....Frrrrr',
    'WWWWWW.........,.............rrrrr',
    'WWWWWW......................Frrrrr',
    'WWWWWW...,..........,.......Frrrrr',
    'WWWWWW......................ffffff',
    'aaaaaa.............,..............',
    'TTTTTTTTTTT.......................',
    'TtttttttttT......,........,.......',
    'Ttttttttttt.......................',
    'TtttttttttT..........,............',
    'TtttttttttT.......................',
  ],
  legend: {
    W: { floor: 'wood', wall: 'plank', wallH: 3.1 },
    a: { floor: 'wood', tint: '#9a7a5a' },
    '~': { floor: 'water' },
    d: { floor: 'deck' },
    D: { floor: 'deck', prop: { type: 'dock_post' } },
    '.': { floor: 'cobble' },
    ',': { floor: 'cobble', tint: '#8a8276' },
    f: { floor: 'cobble', prop: { type: 'fence' } },
    F: { floor: 'cobble', prop: { type: 'fence', rot: 90 } },
    r: { floor: 'metal' },
    T: { floor: 'wood', wall: 'wood', wallH: 2.7 },
    t: { floor: 'wood', tint: '#b8905e' },
  },
}

/** Dressing every version of the aerodock shares. */
export const dockProps: PlacedProp[] = [
  // warehouse fronts
  { type: 'awning', at: [2, 11], rot: 0, params: { w: 2.1 }, color: '#c8b48a' },
  { type: 'awning', at: [4, 11], rot: 0, params: { w: 2.1 }, color: '#c8b48a' },
  { type: 'awning', at: [6, 15], rot: 90, params: { w: 3 }, color: '#a8443a' },
  { type: 'window', at: [6, 2], rot: 90, params: { style: 'wood', shutters: true, lit: false } },
  { type: 'window', at: [6, 6], rot: 90, params: { style: 'wood', lit: false } },
  { type: 'window', at: [6, 18], rot: 90, params: { style: 'wood', shutters: true, lit: false } },
  { type: 'banner', at: [6, 13], rot: 90, params: { wall: true, emblem: 'none' }, color: '#3a5a8a' },
  { type: 'window', at: [2, 12], rot: 180, params: { style: 'wood', lit: false } },
  // the dock tavern
  { type: 'window', at: [3, 22], rot: 0, params: { style: 'wood', light: true } },
  { type: 'window', at: [8, 22], rot: 0, params: { style: 'wood', light: true } },
  { type: 'chalkboard', at: [5, 22], rot: 0, params: { wall: true } },
  { type: 'chalkboard', at: [1, 24], rot: 90, params: { wall: true } },
  { type: 'table', at: [3, 23], params: { items: true } },
  { type: 'table', at: [8, 23], params: { items: true } },
  { type: 'table', at: [4, 25], params: { items: true } },
  { type: 'table', at: [7, 25], params: { round: true, items: true } },
  { type: 'chair', at: [2, 23], rot: 90 },
  { type: 'chair', at: [9, 23], rot: -90 },
  { type: 'chair', at: [5, 25], rot: -90 },
  { type: 'chair', at: [6, 25], rot: 90 },
  { type: 'stool', at: [8, 24] },
  { type: 'candles', at: [3, 23], y: 0.74 },
  { type: 'candles', at: [7, 25], y: 0.74 },
  { type: 'barrel', at: [1, 22] },
  { type: 'barrel', at: [9, 22] },
  { type: 'barrel', at: [1, 25], params: { lying: true } },
  { type: 'lantern', at: [5, 24], params: { style: 'hanging' } },
  { type: 'lantern', at: [11, 22] },
  // boardwalk & quay
  { type: 'lamppost', at: [9, 12] },
  { type: 'lamppost', at: [17, 12] },
  { type: 'lamppost', at: [25, 12] },
  { type: 'lamppost', at: [13, 21] },
  { type: 'lamppost', at: [24, 20] },
  { type: 'rope_coil', at: [9, 9] },
  { type: 'rope_coil', at: [19, 10] },
  { type: 'rope_coil', at: [31, 9] },
  { type: 'rope_coil', at: [11, 5] },
  { type: 'crate', at: [14, 10], params: { stack: 2 } },
  { type: 'crate', at: [15, 10] },
  { type: 'barrel', at: [21, 9] },
  { type: 'barrel', at: [22, 9] },
  { type: 'anchor', at: [33, 10] },
  { type: 'mast', at: [21, 12], color: '#3a5a8a' },
  { type: 'rope_coil', at: [22, 13] },
  // goods, carts, the spice merchants
  { type: 'cart', at: [11, 14], rot: 0 },
  { type: 'sack', at: [12, 13], params: { count: 3 } },
  { type: 'sack', at: [13, 14], params: { count: 2 } },
  { type: 'crate', at: [7, 16], params: { stack: 3 } },
  { type: 'crate', at: [8, 16], params: { stack: 2 } },
  { type: 'crate', at: [7, 17] },
  { type: 'crate', at: [16, 16], params: { stack: 2 } },
  { type: 'crate', at: [17, 17] },
  { type: 'sack', at: [16, 17], params: { count: 3 } },
  { type: 'barrel', at: [25, 18] },
  { type: 'barrel', at: [26, 18] },
  { type: 'barrel', at: [25, 19], params: { lying: true } },
  { type: 'stall', at: [13, 23], rot: 0, color: '#c0602c' },
  { type: 'stall', at: [24, 23], rot: 0, color: '#2f8f8a', params: { goods: 'fish' } },
  { type: 'crate', at: [27, 22], params: { stack: 2 }, color: '#a87040' },
  { type: 'sack', at: [12, 24], params: { count: 2 }, color: '#c8a050' },
  { type: 'basket', at: [16, 24] },
  { type: 'basket', at: [22, 24], params: { fill: 'fish' } },
  // the parts shed (Itaka's wares)
  { type: 'tent', at: [22, 16], rot: 90, color: '#b8a888' },
  { type: 'gear', at: [20, 17], params: { standing: true } },
  { type: 'workbench', at: [23, 18], rot: 0 },
  { type: 'pipe', at: [19, 15], params: { r: 0.14 } },
  // ethanol tanks and the engine test stand
  { type: 'boiler', at: [30, 15], rot: 90 },
  { type: 'boiler', at: [32, 15], rot: 90 },
  { type: 'boiler', at: [31, 18], rot: 90 },
  { type: 'pipe', at: [29, 17], params: { vertical: true } },
  { type: 'propeller', at: [31, 22], rot: -90, params: { speed: 9 } },
  { type: 'workbench', at: [29, 22], rot: 0 },
]

/** Spawn points shared by the aerodock scenes. */
export const dockSpawns: Record<string, Vec2> = {
  street: [18, 25],
  tavern: [5, 23],
  alley: [3, 12],
  itaka: [24, 9],
}

// ============================================================================ Temple of El (32 x 30)

export const templeMap: MapDef = {
  rows: [
    '################################',
    '#mmmmmmmmmmHHHHHHHnHHHHHHHHLLLL#',
    '#mmmmmmmmmmHkkkkkkkkkkkkkHLLLLL#',
    '#mmmmmmmmmmHkKKKKKKKKKKKkHLLLLL#',
    '#mmmmmmmmmmdkKgggggggggKkdLLLLL#',
    '#mmmmmmmmmmdkKgggggggggKkHLLLLL#',
    '#mmmmmmmmmmHkKgggggggggKkHLLLLL#',
    '#mmmmmmmmmmHkKKKKKKKKKKKkHLLLLL#',
    '#ddHHHHHHHHHkkkkkkkkkkkkkHHHHHH#',
    '#aaaaaaaaaaHHHHHHdddHHHHHHHHHHH#',
    '#aaaaaaaaaaaaaaaaaaaaaaaaHSSSSS#',
    '#aaaaaaaaaaaaaaaaaaaaaaaaHSSSSS#',
    'eaaaaaaaaaaaaaaaaaaaaaaaaxSSSSS#',
    '#aaaaaaaaaaaaaaaaaaaaaaaaHSSSSS#',
    '#APAAPAAPAAPAAPAAPAAPAAPAHSSSSS#',
    '#ccccccccccccccccccccccccHSSSSS#',
    '#ccccccccccccccccccccccccHHHHHH#',
    '#ccccccccccccccppcccccccccccccc#',
    'eccccccccccccccppcccccccccccccc#',
    '#ccccccccccccccppcccccccccccccc#',
    '#ccccccccccccccppcccwwwwwcccccc#',
    '#ccccccccccccccppcccwwwwwcccccc#',
    '#ccccccccccccccppcccwwwwwcccccc#',
    '#ccccccccccccccppcccccccccccccc#',
    '#hhhhhcccccccccppccccccccchhhhh#',
    '#ccccccccccccccppcccccccccccccc#',
    '#ccccccccccfffcppcfffcccccccccc#',
    '#ccccccccccccccppcccccccccccccc#',
    '#ccccccccccccccppcccccccccccccc#',
    'lllllllllllllllGGlllllllllllllll',
  ],
  legend: {
    '#': { floor: 'marble', wall: 'white', wallH: 3.6 },
    H: { floor: 'marble', h: 1, wall: 'white', wallH: 3.1 },
    m: { floor: 'marble', h: 1, tint: '#a8a0c8' },
    k: { floor: 'marble', h: 1 },
    K: { floor: 'marble', h: 1, stairs: true, tint: '#e8e2d8' },
    g: { floor: 'moss' },
    n: { floor: 'marble', h: 1, tint: '#c8c0e0', tag: 'niche' },
    L: { floor: 'wood', h: 1, tint: '#9a7a62' },
    S: { floor: 'stone', h: 1, tint: '#b8b0a4' },
    a: { floor: 'marble', h: 1, tint: '#ece6f0' },
    A: { floor: 'marble', h: 1, stairs: true, tint: '#e2dce8' },
    P: { floor: 'marble', h: 1, prop: { type: 'pillar', params: { blocksSight: true, h: 3.0 } } },
    d: { floor: 'marble', h: 1, tint: '#d8d0e8' },
    x: { floor: 'marble', h: 1, tint: '#d8d0e8', tag: 'studydoor' },
    e: { floor: 'marble', tint: '#d8d0e8' },
    c: { floor: 'white' },
    p: { floor: 'marble', tint: '#e6e0f0' },
    w: { floor: 'water' },
    h: { floor: 'grass', wall: 'hedge', wallH: 1.3 },
    f: { floor: 'grass', prop: { type: 'flowers', params: { glow: true } } },
    l: { floor: 'white', wall: 'white', wallH: 1.0 },
    G: { floor: 'marble', tint: '#e6e0f0', tag: 'gate' },
  },
}

/** The temple's permanent dressing (lights and props that suit day and night). */
export const templeProps: PlacedProp[] = [
  // mosaic hall
  { type: 'c4_el_mosaic', at: [5, 1], rot: 0, id: 'el_mosaic' },
  { type: 'mosaic', at: [2, 1], rot: 0 },
  { type: 'mosaic', at: [8, 1], rot: 0 },
  { type: 'mosaic', at: [1, 4], rot: 90 },
  { type: 'candles', at: [3, 3] },
  { type: 'candles', at: [7, 3] },
  { type: 'bench', at: [3, 6], params: { style: 'stone' } },
  { type: 'bench', at: [7, 6], params: { style: 'stone' } },
  { type: 'banner', at: [10, 6], rot: -90, params: { wall: true, emblem: 'star' }, color: '#5a2a8a' },
  // inner garden
  { type: 'fountain', at: [18, 5], params: { glow: true, style: 'white' } },
  { type: 'c4_night_tree', at: [15, 4], params: { glow: '#9a7aff', canopy: '#24506a', size: 1.15 } },
  { type: 'c4_night_tree', at: [21, 6], params: { glow: '#b47aff', canopy: '#2a3e6e', size: 1.1 } },
  { type: 'pillar', at: [13, 3], params: { h: 3.0 } },
  { type: 'pillar', at: [23, 3], params: { h: 3.0 } },
  { type: 'pillar', at: [13, 7], params: { h: 3.0 } },
  { type: 'pillar', at: [23, 7], params: { h: 3.0 } },
  { type: 'pillar', at: [17, 2], params: { h: 3.0 } },
  { type: 'pillar', at: [19, 2], params: { h: 3.0 } },
  { type: 'bench', at: [18, 1], params: { style: 'stone' }, scale: 0.8 },
  { type: 'flowers', at: [16, 6], params: { glow: true } },
  { type: 'flowers', at: [20, 4], params: { glow: true } },
  { type: 'flowers', at: [19, 6] },
  { type: 'mushroom', at: [14, 6], params: { glow: true } },
  { type: 'mushroom', at: [22, 4], params: { glow: true } },
  { type: 'grass', at: [17, 4] },
  { type: 'grass', at: [21, 5] },
  // the library
  { type: 'bookshelf', at: [27, 1], rot: 0 },
  { type: 'bookshelf', at: [29, 1], rot: 0 },
  { type: 'bookshelf', at: [30, 4], rot: -90 },
  { type: 'desk', at: [28, 5], rot: 0 },
  { type: 'candles', at: [28, 5], y: 0.78 },
  // colonnade
  { type: 'banner', at: [4, 9], rot: 0, params: { wall: true, emblem: 'star' }, color: '#5a2a8a' },
  { type: 'banner', at: [14, 10], rot: 0, params: { wall: true, emblem: 'star' }, color: '#5a2a8a' },
  { type: 'banner', at: [22, 10], rot: 0, params: { wall: true, emblem: 'star' }, color: '#5a2a8a' },
  { type: 'bench', at: [3, 13], params: { style: 'stone' } },
  { type: 'bench', at: [9, 13], params: { style: 'stone' }, id: 'gossip_bench' },
  { type: 'bench', at: [15, 13], params: { style: 'stone' } },
  { type: 'bench', at: [21, 13], params: { style: 'stone' } },
  { type: 'lantern', at: [7, 10], params: { style: 'hanging' } },
  { type: 'lantern', at: [17, 11], params: { style: 'hanging' } },
  // Soril's study
  { type: 'window', at: [28, 10], rot: 0, params: { style: 'stone', arch: true } },
  { type: 'table', at: [28, 12] },
  { type: 'chair', at: [28, 11], rot: 0 },
  { type: 'chair', at: [28, 13], rot: 180 },
  { type: 'shelf', at: [30, 11], rot: -90 },
  { type: 'cabinet', at: [30, 14], rot: -90 },
  { type: 'candles', at: [28, 12], y: 0.74 },
  // courtyard
  { type: 'temple_tree', at: [8, 21] },
  { type: 'flowers', at: [6, 23], params: { glow: true } },
  { type: 'flowers', at: [10, 19], params: { glow: true } },
  { type: 'lamppost', at: [13, 18], params: { style: 'brass' } },
  { type: 'lamppost', at: [18, 18], params: { style: 'brass' } },
  { type: 'lamppost', at: [13, 27], params: { style: 'brass' } },
  { type: 'lamppost', at: [18, 27], params: { style: 'brass' } },
  { type: 'brazier', at: [14, 28] },
  { type: 'brazier', at: [17, 28] },
  { type: 'el_statue', at: [26, 21], rot: -45 },
  { type: 'bench', at: [24, 25], params: { style: 'stone', back: true } },
  { type: 'bench', at: [4, 26], params: { style: 'stone', back: true } },
  { type: 'lily', at: [21, 21] },
  { type: 'lily', at: [23, 20] },
  { type: 'bush', at: [28, 18], params: { flowers: true } },
  { type: 'bush', at: [2, 20], params: { flowers: true } },
  { type: 'door', at: [0, 12], rot: 90, params: { style: 'white' } },
  { type: 'door', at: [0, 18], rot: 90, params: { style: 'iron' } },
  { type: 'door', at: [25, 12], rot: 90, params: { style: 'wood', open: true }, solid: false },
  { type: 'gate', at: [15, 29], params: { open: true }, solid: false },
  { type: 'gate', at: [16, 29], params: { open: true }, solid: false },
]

export const templeSpawns: Record<string, Vec2> = {
  side: [1, 12],
  vault: [1, 18],
  gate: [15, 27],
  study: [27, 13],
  niche: [18, 2],
}

// ============================================================================ the garden beyond the old canal (26 x 22)

export const gardenMap: MapDef = {
  rows: [
    '###########WW#############',
    'qqqqqqqqqqqqqqqqqqqqqqqqqq',
    '~~~~~bb~~~~~~~~~~~~~~~~~~~',
    '~~~~~bb~~~~~~~~~~~~~~~~~~~',
    '~~~~~bb~~~~~~~~~~~~~~~~~~~',
    'rrrrr..rrrrsssrrrrrrrrrrr ',
    'o,,,,..,,,,sss,,,,,,,,,,  ',
    'o,ggg..g,,,,..,,ggg,,,,,  ',
    'o,ggg,..,,,,..,gggg,,,,,  ',
    'o,,g,,,..,,,..,,gg,,,,,,  ',
    'O,,,,,,,......,,,,,,,,,   ',
    'o,,,,,ggg,,..,,,,,,,ss,   ',
    'o,,,,gggg,,..,,,,,,,ss,   ',
    'O,,,,,gg,,,,..,,,,,,,,,   ',
    'o,ss,,,,,,,,..,,,ggg,,    ',
    'o,ss,,,,,,,,,..,gggg,,    ',
    'o,,,,,,,,,,,,..,,gg,,     ',
    'O,,ggg,,,,,,,,..,,,,,     ',
    'o,gggg,,,,,,,,,..,,,      ',
    'o,,gg,,,,,,,,,,,.,,,      ',
    'o,,,,,,,,,,,,,,,,,,       ',
    'o,,,,,,,,,,,,,,,,,        ',
  ],
  legend: {
    '#': { floor: 'cobble', wall: 'white', wallH: 2.8 },
    W: { floor: 'cobble', wall: 'brick', wallH: 2.4 },
    q: { floor: 'cobble' },
    '~': { floor: 'canal' },
    b: { floor: 'stone', h: 1, stairs: true, side: 'stone', tint: '#a8a49c' },
    r: { floor: 'rock', tint: '#7a7884' },
    s: { floor: 'stone', tint: '#8c9488' },
    o: { floor: 'moss', wall: 'stone', wallH: 1.5 },
    O: { floor: 'moss', wall: 'stone', wallH: 0.7 },
    '.': { floor: 'dirt' },
    ',': { floor: 'moss', tint: '#6a7a68' },
    g: { floor: 'grass', tint: '#5a7a60' },
  },
}

/** The old garden's crumbling benches, glowing trees, lichen and night flowers. */
export const gardenProps: PlacedProp[] = [
  // far bank
  { type: 'window', at: [3, 1], rot: 0, params: { style: 'white', light: true, flowers: true } },
  { type: 'window', at: [8, 1], rot: 0, params: { style: 'white', lit: false, shutters: true } },
  { type: 'window', at: [16, 1], rot: 0, params: { style: 'white', light: true } },
  { type: 'window', at: [21, 1], rot: 0, params: { style: 'white', lit: false } },
  { type: 'lamppost', at: [9, 1] },
  { type: 'paper_lantern', at: [18, 1], color: '#c08aff' },
  { type: 'railing', at: [4, 2], rot: 90, params: { style: 'stone' } },
  { type: 'railing', at: [7, 2], rot: 90, params: { style: 'stone' } },
  { type: 'railing', at: [4, 4], rot: 90, params: { style: 'stone' } },
  { type: 'railing', at: [7, 4], rot: 90, params: { style: 'stone' } },
  // the bench with the cracked brass armrest, its lamp and tree
  { type: 'bench', at: [12, 6], rot: 0, params: { back: true, style: 'stone' }, color: '#c8c2b4', id: 'bench' },
  { type: 'lamppost', at: [14, 5] },
  { type: 'c4_night_tree', at: [10, 5], params: { size: 1.25 } },
  { type: 'c4_night_tree', at: [19, 7], params: { glow: '#9a7aff', canopy: '#1e4a5e' } },
  { type: 'c4_night_tree', at: [4, 9], params: { size: 1.1, canopy: '#2e3a6a' } },
  { type: 'c4_night_tree', at: [9, 16], params: { glow: '#c48aff' } },
  { type: 'c4_night_tree', at: [20, 12], params: { size: 0.95, dim: true } },
  { type: 'c4_night_tree', at: [15, 18], params: { size: 1.05, canopy: '#22466a' } },
  { type: 'c4_night_tree', at: [3, 18], params: { size: 0.9, dim: true } },
  // crumbling benches and ruins
  { type: 'bench', at: [6, 12], rot: 90, params: { style: 'stone' }, color: '#a8a49a' },
  { type: 'bench', at: [17, 15], rot: 0, params: { style: 'stone' }, color: '#a8a49a' },
  { type: 'pillar', at: [2, 14], params: { broken: true, style: 'stone' } },
  { type: 'pillar', at: [21, 11], params: { broken: true, style: 'stone' } },
  { type: 'statue_pedestal', at: [12, 11], params: { stubs: true } },
  { type: 'boulder', at: [23, 8], params: { size: 0.8 } },
  { type: 'rock', at: [8, 9], params: { moss: true } },
  { type: 'rock', at: [18, 18], params: { moss: true } },
  { type: 'stump', at: [14, 14] },
  // night flowers, lichen, mushrooms, reeds by the water
  { type: 'flowers', at: [7, 6], params: { glow: true } },
  { type: 'flowers', at: [15, 7], params: { glow: true } },
  { type: 'flowers', at: [3, 7], params: { glow: true } },
  { type: 'flowers', at: [18, 9], params: { glow: true } },
  { type: 'flowers', at: [5, 15], params: { glow: true } },
  { type: 'flowers', at: [11, 18], params: { glow: true } },
  { type: 'flowers', at: [19, 16], params: { glow: true } },
  { type: 'c4_lichen', at: [11, 7] },
  { type: 'c4_lichen', at: [13, 9], params: { size: 0.8 } },
  { type: 'c4_lichen', at: [12, 13], params: { size: 1.1 } },
  { type: 'c4_lichen', at: [2, 11], params: { color: '#8fe8ff' } },
  { type: 'c4_lichen', at: [16, 12], params: { color: '#b48aff', size: 0.9 } },
  { type: 'c4_lichen', at: [7, 19] },
  { type: 'c4_lichen', at: [1, 8], params: { wall: true }, rot: 90 },
  { type: 'mushroom', at: [5, 10], params: { glow: true } },
  { type: 'mushroom', at: [22, 14], params: { glow: true } },
  { type: 'mushroom', at: [13, 17], params: { glow: true } },
  { type: 'reeds', at: [2, 5] },
  { type: 'reeds', at: [17, 5] },
  { type: 'reeds', at: [22, 5] },
  { type: 'lily', at: [10, 3] },
  { type: 'lily', at: [19, 2] },
  { type: 'bush', at: [22, 9], params: { flowers: true } },
  { type: 'bush', at: [1, 16] },
  { type: 'bush', at: [17, 10] },
  { type: 'grass', at: [8, 7] },
  { type: 'grass', at: [16, 8] },
  { type: 'grass', at: [6, 17] },
  { type: 'grass', at: [20, 17] },
]

export const gardenSpawns: Record<string, Vec2> = {
  bridge: [6, 1],
  bench: [12, 7],
  path: [13, 16],
}
